apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: itoto
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: patata-caldo
    spec:
      containers:
      - name: api
        image: itoto/patata-caldo:latest
        ports:
        - name: api
          containerPort: 9999