apiVersion: v1
kind: Service
metadata:
  name: itoto
spec:
  selector:
    app: itoto
  ports:
    - port: 80  # Keep this port, so people can reach you through http://[your name]/process
      targetPort: [put the port of your app here]