apiVersion: v1
kind: Service
metadata:
  name: itoto
spec:
  selector:
    app: patata-caldo
  ports:
    - port: 80  # Keep this port, so people can reach you through http://[your name]/process
      targetPort: 9999
  type: LoadBalancer